server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/product_service"
    username: root
    password: Nokidding123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
